### ISSUE TITLE
Repacking mod doesnt apply changes made

### ISSUE THREAD

**Issue by jlaine3333** [Steviegt6/TML.Patcher#19]
I unpacked a mod I wanted to balance (DBZMOD), changed a few things, and repacked it, then replaced the mod in tmodloader's mod folder, but the mod hasn't been changed at all.
TMLP version: 0.2.0.1
TML version: 0.11.8.5
Terraria version: 1.3.5.3

**Comment by omega1084** [comment]
I ran into this problem as well.
I unpack the same mod, make my changes, repack it and replace the mod in the Mods folder for Tmodloader.

When I load into the game none of the changes are taken, in fact I've gone out of my way to break things or use completely ridiculous values to see if something happens but nothing does. The tmod files are just ignored, it's like nothing was done.
I've made new worlds and characters and this persists, none of my changes take effect.

Am I missing a step somewhere? I haven't decompiled or recompiled anything, I simply opened the .cs files and changed values a bit in Visual Studio and repacked because DBZ things are very OP in multiplayer.

**Comment by Steviegt6** [comment]
> 
> 
> I ran into this problem as well. I unpack the same mod, make my changes, repack it and replace the mod in the Mods folder for Tmodloader.
> 
> When I load into the game none of the changes are taken, in fact I've gone out of my way to break things or use completely ridiculous values to see if something happens but nothing does. The tmod files are just ignored, it's like nothing was done. I've made new worlds and characters and this persists, none of my changes take effect.
> 
> Am I missing a step somewhere? I haven't decompiled or recompiled anything, I simply opened the .cs files and changed values a bit in Visual Studio and repacked because DBZ things are very OP in multiplayer.

That's worrying, I may have gotten a path mixed up. I'll have to look into this later.
I don't believe it's an issue on your end.

**Comment by omega1084** [comment]
Good luck!
I'd figured since that other person never responded it was fixed or on my end so I spent all day figuring it out and got nowhere.
Hopefully it's an easy fix.

**Comment by Steviegt6** [comment]
Repacking is currently no longer planned, build your mods in-game.

**Comment by steviegt6** [comment]
Oh yeah FYI this has been rectified, packing your mods should work fine.
